### ISSUE TITLE
Which test to run to simulate element not found and which test to understand Healenium fix?

### ISSUE THREAD

**Issue by PavanDuvvuri** [healenium/healenium-example-dotnet#1]
Can someone pls elaborate how to fail the tests and validate the healenium fixing it? and I dont see any DLL for Healenium like I see a JAR for java, how it works?

**Comment by ElenaStepuro** [comment]
Hello @PavanDuvvuri !
.NET based tests are working via Healenium Proxy. All healenium components setup by docker-compose file which you can find in example. This is like an alternative for DLL and Java jar file.
Also, you're creating RemoteWebDriver by URL http://<your-host>:8085 instead of delegating to SelfHealingDriver.
So, to fail test and validate the healing works you just need to change RemoteWebDriver URL or to run it locally.

**Comment by CraigRichards** [comment]
Hi @ElenaStepuro,
I'm very interested in understanding what is going on also. The project looks amazing and I've watched a bunch of your YouTube videos.

**HealeniumProxy**
I'm trying to understand what the different components do but the HealeniumProxy ReadMe.md is blank. What do I do with this component?

**SelfHealingDriver**
You mentioned a SelfHealingDriver but I could not find any reference to it in this project. Is there a Nuget package for this?

**How to run tests**
I'm trying to run the project myself it failes for me and wondering if you can help. I get a null reference exception when instanciating the driver.

**Comment by ElenaStepuro** [comment]
Hellp @CraigRichards ,

To start using Healenium-Proxy you need to follow 2 simple steps:

1. start docker-compose as in example https://github.com/healenium/healenium-example-dotnet/blob/master/infra/docker-compose.yml
2. and create RemoteWebDriver using URL "http://<your host>:8085"

For monitoring tests run use this link http://<your host>:8086

As about SelfHealingDriver, you don't need it with Proxy.

However, we're planning to add Proxy video tutorials on YouTube in the near future.

**Comment by CraigRichards** [comment]
Thabks for the reply. I will give this a go again.
